/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuditRegistry {
  export type AuditRecordStruct = {
    auditId: BigNumberish;
    contractAddr: AddressLike;
    reportHash: BytesLike;
    merkleRoot: BytesLike;
    reportCID: string;
    auditor: AddressLike;
    timestamp: BigNumberish;
    blockNumber: BigNumberish;
    score: BigNumberish;
  };

  export type AuditRecordStructOutput = [
    auditId: bigint,
    contractAddr: string,
    reportHash: string,
    merkleRoot: string,
    reportCID: string,
    auditor: string,
    timestamp: bigint,
    blockNumber: bigint,
    score: bigint
  ] & {
    auditId: bigint;
    contractAddr: string;
    reportHash: string;
    merkleRoot: string;
    reportCID: string;
    auditor: string;
    timestamp: bigint;
    blockNumber: bigint;
    score: bigint;
  };
}

export interface AuditRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuditor"
      | "authorisedAuditors"
      | "getAudit"
      | "getAuditHistory"
      | "owner"
      | "removeAuditor"
      | "renounceOwnership"
      | "submitAudit"
      | "totalAudits"
      | "transferOwnership"
      | "verifyReport"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditSubmitted"
      | "AuditorAdded"
      | "AuditorRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorisedAuditors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAudit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitAudit",
    values: [AddressLike, BytesLike, BytesLike, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAudits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyReport",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAuditor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorisedAuditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAudit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuditHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAudits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyReport",
    data: BytesLike
  ): Result;
}

export namespace AuditSubmittedEvent {
  export type InputTuple = [
    auditId: BigNumberish,
    contractAddr: AddressLike,
    reportHash: BytesLike,
    merkleRoot: BytesLike,
    reportCID: string,
    auditor: AddressLike,
    score: BigNumberish
  ];
  export type OutputTuple = [
    auditId: bigint,
    contractAddr: string,
    reportHash: string,
    merkleRoot: string,
    reportCID: string,
    auditor: string,
    score: bigint
  ];
  export interface OutputObject {
    auditId: bigint;
    contractAddr: string;
    reportHash: string;
    merkleRoot: string;
    reportCID: string;
    auditor: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorAddedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditorRemovedEvent {
  export type InputTuple = [auditor: AddressLike];
  export type OutputTuple = [auditor: string];
  export interface OutputObject {
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuditRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuditRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuditor: TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;

  authorisedAuditors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAudit: TypedContractMethod<
    [contractAddr: AddressLike],
    [AuditRegistry.AuditRecordStructOutput],
    "view"
  >;

  getAuditHistory: TypedContractMethod<
    [contractAddr: AddressLike],
    [AuditRegistry.AuditRecordStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAuditor: TypedContractMethod<
    [auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitAudit: TypedContractMethod<
    [
      contractAddr: AddressLike,
      reportHash: BytesLike,
      merkleRoot: BytesLike,
      reportCID: string,
      auditorSig: BytesLike,
      score: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  totalAudits: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyReport: TypedContractMethod<
    [contractAddr: AddressLike, reportHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuditor"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorisedAuditors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAudit"
  ): TypedContractMethod<
    [contractAddr: AddressLike],
    [AuditRegistry.AuditRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditHistory"
  ): TypedContractMethod<
    [contractAddr: AddressLike],
    [AuditRegistry.AuditRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAuditor"
  ): TypedContractMethod<[auditor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitAudit"
  ): TypedContractMethod<
    [
      contractAddr: AddressLike,
      reportHash: BytesLike,
      merkleRoot: BytesLike,
      reportCID: string,
      auditorSig: BytesLike,
      score: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAudits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyReport"
  ): TypedContractMethod<
    [contractAddr: AddressLike, reportHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuditSubmitted"
  ): TypedContractEvent<
    AuditSubmittedEvent.InputTuple,
    AuditSubmittedEvent.OutputTuple,
    AuditSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorAdded"
  ): TypedContractEvent<
    AuditorAddedEvent.InputTuple,
    AuditorAddedEvent.OutputTuple,
    AuditorAddedEvent.OutputObject
  >;
  getEvent(
    key: "AuditorRemoved"
  ): TypedContractEvent<
    AuditorRemovedEvent.InputTuple,
    AuditorRemovedEvent.OutputTuple,
    AuditorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AuditSubmitted(uint256,address,bytes32,bytes32,string,address,uint256)": TypedContractEvent<
      AuditSubmittedEvent.InputTuple,
      AuditSubmittedEvent.OutputTuple,
      AuditSubmittedEvent.OutputObject
    >;
    AuditSubmitted: TypedContractEvent<
      AuditSubmittedEvent.InputTuple,
      AuditSubmittedEvent.OutputTuple,
      AuditSubmittedEvent.OutputObject
    >;

    "AuditorAdded(address)": TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;
    AuditorAdded: TypedContractEvent<
      AuditorAddedEvent.InputTuple,
      AuditorAddedEvent.OutputTuple,
      AuditorAddedEvent.OutputObject
    >;

    "AuditorRemoved(address)": TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;
    AuditorRemoved: TypedContractEvent<
      AuditorRemovedEvent.InputTuple,
      AuditorRemovedEvent.OutputTuple,
      AuditorRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
