/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace AgentMarketplace {
  export type AgentStruct = {
    agentId: string;
    operator: AddressLike;
    teeEndpoint: string;
    encPubKey: BytesLike;
    stake: BigNumberish;
    tokenId: BigNumberish;
    jobsCompleted: BigNumberish;
    jobsFailed: BigNumberish;
    registeredAt: BigNumberish;
    status: BigNumberish;
  };

  export type AgentStructOutput = [
    agentId: string,
    operator: string,
    teeEndpoint: string,
    encPubKey: string,
    stake: bigint,
    tokenId: bigint,
    jobsCompleted: bigint,
    jobsFailed: bigint,
    registeredAt: bigint,
    status: bigint
  ] & {
    agentId: string;
    operator: string;
    teeEndpoint: string;
    encPubKey: string;
    stake: bigint;
    tokenId: bigint;
    jobsCompleted: bigint;
    jobsFailed: bigint;
    registeredAt: bigint;
    status: bigint;
  };

  export type JobStruct = {
    jobId: BigNumberish;
    requester: AddressLike;
    agentKey: BytesLike;
    encryptedPayload: BytesLike;
    payloadHash: BytesLike;
    resultCID: string;
    resultHash: BytesLike;
    fee: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    status: BigNumberish;
  };

  export type JobStructOutput = [
    jobId: bigint,
    requester: string,
    agentKey: string,
    encryptedPayload: string,
    payloadHash: string,
    resultCID: string,
    resultHash: string,
    fee: bigint,
    createdAt: bigint,
    completedAt: bigint,
    status: bigint
  ] & {
    jobId: bigint;
    requester: string;
    agentKey: string;
    encryptedPayload: string;
    payloadHash: string;
    resultCID: string;
    resultHash: string;
    fee: bigint;
    createdAt: bigint;
    completedAt: bigint;
    status: bigint;
  };
}

export interface AgentMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_WINDOW"
      | "JOB_EXPIRY"
      | "MIN_STAKE"
      | "createJob"
      | "disputeJob"
      | "getAgent"
      | "getAgentJobs"
      | "getJob"
      | "getOperatorAgents"
      | "getRequesterJobs"
      | "isAgentAvailable"
      | "owner"
      | "platformFeeAccrued"
      | "platformFeeBps"
      | "registerAgent"
      | "renounceOwnership"
      | "resolveDispute"
      | "setPlatformFee"
      | "setTokenId"
      | "submitResult"
      | "topUpStake"
      | "totalJobs"
      | "transferOwnership"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentSlashed"
      | "AgentStakeUpdated"
      | "AgentStatusChanged"
      | "JobCompleted"
      | "JobCreated"
      | "JobDisputed"
      | "JobFailed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JOB_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [string, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentJobs",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequesterJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentAvailable",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeAccrued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenId",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "topUpStake", values: [string]): string;
  encodeFunctionData(functionFragment: "totalJobs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "JOB_EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputeJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequesterJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgentAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTokenId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topUpStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentKey: BytesLike,
    agentId: string,
    operator: AddressLike,
    teeEndpoint: string,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    agentKey: string,
    agentId: string,
    operator: string,
    teeEndpoint: string,
    stake: bigint
  ];
  export interface OutputObject {
    agentKey: string;
    agentId: string;
    operator: string;
    teeEndpoint: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentSlashedEvent {
  export type InputTuple = [agentKey: BytesLike, slashedAmount: BigNumberish];
  export type OutputTuple = [agentKey: string, slashedAmount: bigint];
  export interface OutputObject {
    agentKey: string;
    slashedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStakeUpdatedEvent {
  export type InputTuple = [agentKey: BytesLike, newStake: BigNumberish];
  export type OutputTuple = [agentKey: string, newStake: bigint];
  export interface OutputObject {
    agentKey: string;
    newStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentKey: BytesLike, status: BigNumberish];
  export type OutputTuple = [agentKey: string, status: bigint];
  export interface OutputObject {
    agentKey: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    agentKey: BytesLike,
    resultCID: string,
    resultHash: BytesLike
  ];
  export type OutputTuple = [
    jobId: bigint,
    agentKey: string,
    resultCID: string,
    resultHash: string
  ];
  export interface OutputObject {
    jobId: bigint;
    agentKey: string;
    resultCID: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    requester: AddressLike,
    agentKey: BytesLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    requester: string,
    agentKey: string,
    fee: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
    agentKey: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobDisputedEvent {
  export type InputTuple = [jobId: BigNumberish, disputer: AddressLike];
  export type OutputTuple = [jobId: bigint, disputer: string];
  export interface OutputObject {
    jobId: bigint;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFailedEvent {
  export type InputTuple = [jobId: BigNumberish, agentKey: BytesLike];
  export type OutputTuple = [jobId: bigint, agentKey: string];
  export interface OutputObject {
    jobId: bigint;
    agentKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMarketplace;
  waitForDeployment(): Promise<this>;

  interface: AgentMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  JOB_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  createJob: TypedContractMethod<
    [
      agentId: string,
      agentOperator: AddressLike,
      encryptedPayload: BytesLike,
      payloadHash: BytesLike
    ],
    [bigint],
    "payable"
  >;

  disputeJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [AgentMarketplace.AgentStructOutput],
    "view"
  >;

  getAgentJobs: TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [bigint[]],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [AgentMarketplace.JobStructOutput],
    "view"
  >;

  getOperatorAgents: TypedContractMethod<
    [operator: AddressLike],
    [string[]],
    "view"
  >;

  getRequesterJobs: TypedContractMethod<
    [requester: AddressLike],
    [bigint[]],
    "view"
  >;

  isAgentAvailable: TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeAccrued: TypedContractMethod<[], [bigint], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [agentId: string, teeEndpoint: string, encPubKey: BytesLike],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [jobId: BigNumberish, slashAgent: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenId: TypedContractMethod<
    [agentId: string, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [jobId: BigNumberish, resultCID: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  topUpStake: TypedContractMethod<[agentId: string], [void], "payable">;

  totalJobs: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "JOB_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      agentId: string,
      agentOperator: AddressLike,
      encryptedPayload: BytesLike,
      payloadHash: BytesLike
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [AgentMarketplace.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentJobs"
  ): TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [AgentMarketplace.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOperatorAgents"
  ): TypedContractMethod<[operator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRequesterJobs"
  ): TypedContractMethod<[requester: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isAgentAvailable"
  ): TypedContractMethod<
    [agentId: string, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeAccrued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: string, teeEndpoint: string, encPubKey: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [jobId: BigNumberish, slashAgent: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenId"
  ): TypedContractMethod<
    [agentId: string, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [jobId: BigNumberish, resultCID: string, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "topUpStake"
  ): TypedContractMethod<[agentId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "totalJobs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentSlashed"
  ): TypedContractEvent<
    AgentSlashedEvent.InputTuple,
    AgentSlashedEvent.OutputTuple,
    AgentSlashedEvent.OutputObject
  >;
  getEvent(
    key: "AgentStakeUpdated"
  ): TypedContractEvent<
    AgentStakeUpdatedEvent.InputTuple,
    AgentStakeUpdatedEvent.OutputTuple,
    AgentStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobDisputed"
  ): TypedContractEvent<
    JobDisputedEvent.InputTuple,
    JobDisputedEvent.OutputTuple,
    JobDisputedEvent.OutputObject
  >;
  getEvent(
    key: "JobFailed"
  ): TypedContractEvent<
    JobFailedEvent.InputTuple,
    JobFailedEvent.OutputTuple,
    JobFailedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(bytes32,string,address,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentSlashed(bytes32,uint256)": TypedContractEvent<
      AgentSlashedEvent.InputTuple,
      AgentSlashedEvent.OutputTuple,
      AgentSlashedEvent.OutputObject
    >;
    AgentSlashed: TypedContractEvent<
      AgentSlashedEvent.InputTuple,
      AgentSlashedEvent.OutputTuple,
      AgentSlashedEvent.OutputObject
    >;

    "AgentStakeUpdated(bytes32,uint256)": TypedContractEvent<
      AgentStakeUpdatedEvent.InputTuple,
      AgentStakeUpdatedEvent.OutputTuple,
      AgentStakeUpdatedEvent.OutputObject
    >;
    AgentStakeUpdated: TypedContractEvent<
      AgentStakeUpdatedEvent.InputTuple,
      AgentStakeUpdatedEvent.OutputTuple,
      AgentStakeUpdatedEvent.OutputObject
    >;

    "AgentStatusChanged(bytes32,uint8)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "JobCompleted(uint256,bytes32,string,bytes32)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,bytes32,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobDisputed(uint256,address)": TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;
    JobDisputed: TypedContractEvent<
      JobDisputedEvent.InputTuple,
      JobDisputedEvent.OutputTuple,
      JobDisputedEvent.OutputObject
    >;

    "JobFailed(uint256,bytes32)": TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
    JobFailed: TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
