/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IERC8004 {
  export type AgentRecordStruct = {
    agentId: string;
    modelHash: BytesLike;
    operator: AddressLike;
    capabilityHash: BytesLike;
    metadataURI: string;
    trustScore: BigNumberish;
    mintedAt: BigNumberish;
    isRevoked: boolean;
  };

  export type AgentRecordStructOutput = [
    agentId: string,
    modelHash: string,
    operator: string,
    capabilityHash: string,
    metadataURI: string,
    trustScore: bigint,
    mintedAt: bigint,
    isRevoked: boolean
  ] & {
    agentId: string;
    modelHash: string;
    operator: string;
    capabilityHash: string;
    metadataURI: string;
    trustScore: bigint;
    mintedAt: bigint;
    isRevoked: boolean;
  };
}

export interface IERC8004Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAgentsByOperator"
      | "mintCredential"
      | "revokeCredential"
      | "updateScore"
      | "verifyAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "CredentialRevoked"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAgentsByOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCredential",
    values: [string, BytesLike, AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAgentsByOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    agentId: string,
    operator: AddressLike,
    modelHash: BytesLike,
    trustScore: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    agentId: string,
    operator: string,
    modelHash: string,
    trustScore: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    agentId: string;
    operator: string;
    modelHash: string;
    trustScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [tokenId: BigNumberish, reason: string];
  export type OutputTuple = [tokenId: bigint, reason: string];
  export interface OutputObject {
    tokenId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldScore: BigNumberish,
    newScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldScore: bigint,
    newScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldScore: bigint;
    newScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC8004 extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004;
  waitForDeployment(): Promise<this>;

  interface: IERC8004Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAgentsByOperator: TypedContractMethod<
    [operator: AddressLike],
    [bigint[]],
    "view"
  >;

  mintCredential: TypedContractMethod<
    [
      agentId: string,
      modelHash: BytesLike,
      operator: AddressLike,
      capabilityHash: BytesLike,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [tokenId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  updateScore: TypedContractMethod<
    [tokenId: BigNumberish, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  verifyAgent: TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC8004.AgentRecordStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAgentsByOperator"
  ): TypedContractMethod<[operator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "mintCredential"
  ): TypedContractMethod<
    [
      agentId: string,
      modelHash: BytesLike,
      operator: AddressLike,
      capabilityHash: BytesLike,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [tokenId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newScore: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IERC8004.AgentRecordStructOutput],
    "view"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,string,address,bytes32,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "CredentialRevoked(uint256,string)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "ScoreUpdated(uint256,uint256,uint256,string)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
