

export const SEED_AGENTS = [
  {
    id:           "agt_sec_001",
    name:         "ShieldScan Pro",
    operator:     "0xNexusSecurity",
    version:      "2.3",
    status:       "online"  as const,
    trustScore:   91,
    capabilities: ["static-analysis", "dependency-audit", "secret-detection", "reentrancy"],
    stakeAmount:  "500",
    auditCount:   1847,
    model:        "Phala TEE (Intel SGX)",
    teeEndpoint:  "https://phat.phala.network/contracts/get/0x0001",
    badge:        "Verified TEE",
    responseTime: "~45s",
  },
  {
    id:           "agt_sec_002",
    name:         "VaultAudit",
    operator:     "0xChainGuard",
    version:      "1.8",
    status:       "online"  as const,
    trustScore:   88,
    capabilities: ["static-analysis", "formal-verification", "gas-optimisation", "access-control"],
    stakeAmount:  "300",
    auditCount:   934,
    model:        "Phala TEE (Intel SGX)",
    teeEndpoint:  "https://phat.phala.network/contracts/get/0x0002",
    badge:        "Verified TEE",
    responseTime: "~60s",
  },
  {
    id:           "agt_sec_003",
    name:         "ZeroTrace",
    operator:     "0xStealthDAO",
    version:      "3.1",
    status:       "online"  as const,
    trustScore:   94,
    capabilities: ["secret-detection", "ip-theft-prevention", "licence-compliance", "obfuscation-check"],
    stakeAmount:  "750",
    auditCount:   412,
    model:        "Phala TEE (Intel SGX)",
    teeEndpoint:  "https://phat.phala.network/contracts/get/0x0003",
    badge:        "Top Rated",
    responseTime: "~30s",
  },
  {
    id:           "agt_sec_004",
    name:         "DeepSec AI",
    operator:     "0xAutonomousAudit",
    version:      "1.2",
    status:       "busy"    as const,
    trustScore:   86,
    capabilities: ["ai-vulnerability-detection", "pattern-matching", "behaviour-analysis"],
    stakeAmount:  "200",
    auditCount:   267,
    model:        "Phala TEE (Intel SGX)",
    teeEndpoint:  "https://phat.phala.network/contracts/get/0x0004",
    badge:        "AI-Powered",
    responseTime: "~90s",
  },
  {
    id:           "agt_sec_005",
    name:         "PrivacyGuard",
    operator:     "0xZKLabs",
    version:      "4.0",
    status:       "online"  as const,
    trustScore:   97,
    capabilities: ["privacy-analysis", "data-leak-detection", "gdpr-compliance", "zk-readiness"],
    stakeAmount:  "1000",
    auditCount:   183,
    model:        "Phala TEE (Intel SGX)",
    teeEndpoint:  "https://phat.phala.network/contracts/get/0x0005",
    badge:        "ZK Specialist",
    responseTime: "~120s",
  },
];
