/* config/seedAgents.ts — mirrors frontend constants/agents.js */

export const SEED_AGENTS = [
  { id: "agt_sec_001", name: "ShieldScan Pro",  operator: "Nexus Security Labs",   auditCount: 1847, avgScore: 91, stake: "500 AVAX",  status: "online",  teeProvider: "Phala Network (Intel SGX)", capabilities: ["static-analysis","dependency-audit","secret-detection","reentrancy"],                    languages: ["Solidity","Python","JavaScript","Rust","Go"],          responseTime: "~45s",  badge: "Verified TEE"   },
  { id: "agt_sec_002", name: "VaultAudit",       operator: "ChainGuard Protocol",   auditCount: 934,  avgScore: 88, stake: "300 AVAX",  status: "online",  teeProvider: "Phala Network (Intel SGX)", capabilities: ["static-analysis","formal-verification","gas-optimisation","access-control"],            languages: ["Solidity","Vyper","Move"],                             responseTime: "~60s",  badge: "Verified TEE"   },
  { id: "agt_sec_003", name: "ZeroTrace",        operator: "Stealth Audit DAO",     auditCount: 412,  avgScore: 94, stake: "750 AVAX",  status: "online",  teeProvider: "Phala Network (Intel SGX)", capabilities: ["secret-detection","ip-theft-prevention","licence-compliance","obfuscation-check"],      languages: ["JavaScript","TypeScript","Python","Java","C++"],       responseTime: "~30s",  badge: "Top Rated"      },
  { id: "agt_sec_004", name: "DeepSec AI",       operator: "Autonomous Audit Inc.", auditCount: 267,  avgScore: 86, stake: "200 AVAX",  status: "busy",    teeProvider: "Phala Network (Intel SGX)", capabilities: ["ai-vulnerability-detection","pattern-matching","behaviour-analysis"],                   languages: ["Python","Rust","Go","Solidity"],                       responseTime: "~90s",  badge: "AI-Powered"     },
  { id: "agt_sec_005", name: "PrivacyGuard",     operator: "Zero-Knowledge Labs",   auditCount: 183,  avgScore: 97, stake: "1000 AVAX", status: "online",  teeProvider: "Phala Network (Intel SGX)", capabilities: ["privacy-analysis","data-leak-detection","gdpr-compliance","zk-readiness"],              languages: ["Circom","Noir","JavaScript","Python"],                 responseTime: "~120s", badge: "ZK Specialist"  },
];
