/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IntentVault {
  export type IntentStruct = {
    intentId: BytesLike;
    submitter: AddressLike;
    spec: string;
    status: BigNumberish;
    resultCID: string;
    success: boolean;
    submittedAt: BigNumberish;
    executedAt: BigNumberish;
    nonce: BigNumberish;
  };

  export type IntentStructOutput = [
    intentId: string,
    submitter: string,
    spec: string,
    status: bigint,
    resultCID: string,
    success: boolean,
    submittedAt: bigint,
    executedAt: bigint,
    nonce: bigint
  ] & {
    intentId: string;
    submitter: string;
    spec: string;
    status: bigint;
    resultCID: string;
    success: boolean;
    submittedAt: bigint;
    executedAt: bigint;
    nonce: bigint;
  };
}

export interface IntentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExecutor"
      | "authorisedExecutors"
      | "cancelIntent"
      | "getIntent"
      | "getIntentStatus"
      | "getUserIntents"
      | "markExecuted"
      | "nonces"
      | "owner"
      | "removeExecutor"
      | "renounceOwnership"
      | "submitIntent"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "IntentCancelled"
      | "IntentExecuted"
      | "IntentSubmitted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorisedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserIntents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExecuted",
    values: [BytesLike, boolean, string]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitIntent",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorisedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentCancelledEvent {
  export type InputTuple = [intentId: BytesLike];
  export type OutputTuple = [intentId: string];
  export interface OutputObject {
    intentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    success: boolean,
    resultCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    success: boolean,
    resultCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    success: boolean;
    resultCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentSubmittedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    submitter: AddressLike,
    spec: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    submitter: string,
    spec: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    submitter: string;
    spec: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntentVault extends BaseContract {
  connect(runner?: ContractRunner | null): IntentVault;
  waitForDeployment(): Promise<this>;

  interface: IntentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorisedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  cancelIntent: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getIntent: TypedContractMethod<
    [intentId: BytesLike],
    [IntentVault.IntentStructOutput],
    "view"
  >;

  getIntentStatus: TypedContractMethod<[intentId: BytesLike], [bigint], "view">;

  getUserIntents: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  markExecuted: TypedContractMethod<
    [intentId: BytesLike, success: boolean, resultCID: string],
    [void],
    "nonpayable"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitIntent: TypedContractMethod<
    [spec: string, signature: BytesLike],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorisedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelIntent"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [IntentVault.IntentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIntentStatus"
  ): TypedContractMethod<[intentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserIntents"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "markExecuted"
  ): TypedContractMethod<
    [intentId: BytesLike, success: boolean, resultCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitIntent"
  ): TypedContractMethod<
    [spec: string, signature: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "IntentCancelled"
  ): TypedContractEvent<
    IntentCancelledEvent.InputTuple,
    IntentCancelledEvent.OutputTuple,
    IntentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "IntentExecuted"
  ): TypedContractEvent<
    IntentExecutedEvent.InputTuple,
    IntentExecutedEvent.OutputTuple,
    IntentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "IntentSubmitted"
  ): TypedContractEvent<
    IntentSubmittedEvent.InputTuple,
    IntentSubmittedEvent.OutputTuple,
    IntentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ExecutorAdded(address)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "IntentCancelled(bytes32)": TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;
    IntentCancelled: TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;

    "IntentExecuted(bytes32,bool,string,uint256)": TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;
    IntentExecuted: TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;

    "IntentSubmitted(bytes32,address,string,uint256)": TypedContractEvent<
      IntentSubmittedEvent.InputTuple,
      IntentSubmittedEvent.OutputTuple,
      IntentSubmittedEvent.OutputObject
    >;
    IntentSubmitted: TypedContractEvent<
      IntentSubmittedEvent.InputTuple,
      IntentSubmittedEvent.OutputTuple,
      IntentSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
